# Basic config
theme = "hution"
baseURL = "https://jorgechato.com"
title = "jorgechato"
description = "Experiments, stories and ideas."
languageCode = "en"
paginate = 10

enableEmoji = true
pygmentsUseClasses = true

googleAnalytics = "UA-146816931-1"

[taxonomies]
author = "author"
tag = "tags"
category = "categories"

# Router
[permalinks]
post = "/:title"

[params]
mainSections = ["post"]
favicon = "/img/favicon.png"

# Nav
[[params.nav]]
name = "Where is jorge Today?"
url = "https://whereisjorge.today/"
weight = 1

[[params.nav]]
name = "Hacking"
url = "tags/hack"
weight = 2

[[params.nav]]
name = "Coding"
url = "tags/code"
weight = 3

[[params.nav]]
name = "About me"
url = "author/jorge"
weight = 4

# Social
[[params.social]]
name="twitter"
url="https://twitter.com/jorgechato"
icon="fab fa-twitter"

[[params.social]]
name="github"
url="https://github.com/jorgechato"
icon="fab fa-github"

[[params.social]]
name="linkedin"
url="https://www.linkedin.com/in/jorgechato/"
icon="fab fa-linkedin"
